name: 00 - Branch Promotion Auto-PR

on:
  workflow_dispatch:

jobs:
  PromoteBranch:
    runs-on: ubuntu-latest
    steps:
    - name: Determine Source and Target Branch
      id: branches
      run: |
        if [[ "${GITHUB_REF}" == "refs/heads/develop" ]]; then
          echo "source=develop" >> $GITHUB_ENV
          echo "target=integration" >> $GITHUB_ENV
        elif [[ "${GITHUB_REF}" == "refs/heads/integration" ]]; then
          echo "source=integration" >> $GITHUB_ENV
          echo "target=main" >> $GITHUB_ENV
        else
          echo "Invalid source branch"
          exit 1
        fi
      shell: bash
    
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ env.target }}

    - name: Reset promotion branch
      run: |
        git fetch origin ${{ env.source }}:${{ env.source }}
        git reset --hard ${{ env.source }}

    - name: Set current date as env variable
      run: echo "datetime=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Promote ${{ env.source }} to ${{ env.target }}'
        branch: pr-${{ env.source }}-to-${{ env.target }}
        delete-branch: true
        base: ${{ env.target }}
        head: ${{ env.source }}
        title: '[Auto] ${{ env.datetime }} - Promote "${{ env.source }}" to "${{ env.target }}"'
        body: |
          This is an automated pull request to merge changes from ${{ env.source }} to ${{ env.target }}.
          The workflow was triggered by : ${{ github.actor }}
          PR generated at: ${{ env.datetime }}
        reviewers: karimfaiz
        labels: |
          automated pr
        assignees: ${{ github.actor }}
        draft: false
        signoff: false
        author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
        committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.3"
        with:
          permissions: write
          token: ${{ secrets.GITHUB_TOKEN }}
