name: Branch Promotion

on:
  workflow_dispatch:

jobs:
  PromoteBranch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Determine Source and Target Branch
      id: branches
      run: |
        if [[ "${GITHUB_REF}" == "refs/heads/develop" ]]; then
          echo "source=develop" >> $GITHUB_ENV
          echo "target=integration" >> $GITHUB_ENV
        elif [[ "${GITHUB_REF}" == "refs/heads/integration" ]]; then
          echo "source=integration" >> $GITHUB_ENV
          echo "target=main" >> $GITHUB_ENV
        else
          echo "Invalid source branch"
          exit 1
        fi
      shell: bash
    - name: Checkout to a different branch
      run: git checkout main

    - name: Reset promotion branch
      run: |
        git fetch origin ${{ env.source }}:${{ env.source }}
        git reset --hard ${{ env.source }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Promote ${{ env.source }} to ${{ env.target }}'
        branch: pr-${{ env.source }}-to-${{ env.target }}
        delete-branch: true
        base: ${{ env.target }}
        head: ${{ env.source }}
        title: 'Promote ${{ env.source }} to ${{ env.target }}'
        body: |
          This is an automated pull request to merge changes from ${{ env.source }} to ${{ env.target }}.
        reviewers: karimfaiz