name: Branch Promotion

on:
  workflow_dispatch:

jobs:
  PromoteBranch:
    runs-on: ubuntu-latest
    steps:
    - name: Determine Source and Target Branch
      id: branches
      run: |
        if [[ "${GITHUB_REF}" == "refs/heads/develop" ]]; then
          echo "source=develop" >> $GITHUB_ENV
          echo "target=integration" >> $GITHUB_ENV
        elif [[ "${GITHUB_REF}" == "refs/heads/integration" ]]; then
          echo "source=integration" >> $GITHUB_ENV
          echo "target=main" >> $GITHUB_ENV
        else
          echo "Invalid source branch"
          exit 1
        fi
      shell: bash
    
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ env.target }}

    - name: Reset promotion branch
      run: |
        git fetch origin ${{ env.source }}:${{ env.source }}
        git reset --hard ${{ env.source }}