name: Move to Next Env

on:
  workflow_dispatch:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Determine Source and Target Branch
      id: branches
      run: |
        if [[ "${GITHUB_REF}" == "refs/heads/develop" ]]; then
          echo "source=develop" >> $GITHUB_ENV
          echo "target=integration" >> $GITHUB_ENV
        elif [[ "${GITHUB_REF}" == "refs/heads/integration" ]]; then
          echo "source=integration" >> $GITHUB_ENV
          echo "target=main" >> $GITHUB_ENV
        else
          echo "Invalid source branch"
          exit 1
        fi
      shell: bash

    - name: Create Pull Request
      id: create_pr
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Move code from ${{ env.source }} to ${{ env.target }}'
        committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: pr-${{ env.source }}-to-${{ env.target }}
        delete-branch: true
        base: ${{ env.target }}
        head: ${{ env.source }}
        title: 'Move code from ${{ env.source }} to ${{ env.target }}'
        body: |
          Automated PR to move code from ${{ env.source }} branch to ${{ env.target }} branch.
        labels: |
          automated-pr
        assignees: ${{ github.actor }}
        draft: false

  automerge:
    runs-on: ubuntu-latest
    needs: create-pull-request

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Automerge the Pull Request
      id: automerge
      uses: "pascalgn/automerge-action@v0.16.3"
      permissions:
          contents: write
      env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"