name: Move to Next Env

on:
  workflow_dispatch:
    inputs:
      source:
        description: 'Source branch'
        required: true
        default: 'develop'
        type: string

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Determine Source and Target Branch
      id: branches
      run: |
        if [ "${{ github.event.inputs.source }}" == "develop" ]; then
          echo "source=develop" >> $GITHUB_ENV
          echo "target=integration" >> $GITHUB_ENV
        elif [ "${{ github.event.inputs.source }}" == "integration" ]; then
          echo "source=integration" >> $GITHUB_ENV
          echo "target=main" >> $GITHUB_ENV
        else
          echo "Invalid source branch"
          exit 1

    - name: Create Pull Request
      id: create_pr
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        base: ${{ env.target }}
        head: ${{ env.source }}
        title: 'Move code from ${{ env.source }} to ${{ env.target }}'
        body: 'Automated PR to move code from ${{ env.source }} branch to ${{ env.target }} branch'

  merge-pull-request:
    runs-on: ubuntu-latest
    needs: create-pull-request

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Merge the Pull Request
      uses: actions/github-script@v6
      with:
        script: |
          const pr_number = '${{ steps.create_pr.outputs.pull_request_number }}';
          if (pr_number) {
            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number,
              merge_method: 'merge',
            });
          } else {
            console.log('No pull request created to merge.');
          }
